/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Connections.ProdutoConnection;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class HomeProduto extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public HomeProduto() {
        initComponents();

        ProdutoConnection produtoConnection = new ProdutoConnection();
        produtoConnection.handleSearch(tbl_tabelaProduto);
        tbl_tabelaProduto.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int selectedRow = tbl_tabelaProduto.getSelectedRow();
                    if (selectedRow != -1) {
                        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                        try {
                            Date dataFabri = dateFormat.parse(tbl_tabelaProduto.getValueAt(selectedRow, 1).toString());
                            String nome = tbl_tabelaProduto.getValueAt(selectedRow, 2).toString();

                            txt_Fabricacao.setText(dateFormat.format(dataFabri));
                            txt_Nome.setText(nome);
                        } catch (ParseException e) {
                        }
                    }
                }
            }
        });
        List<Map<String, Object>> fornecedores = produtoConnection.getNomesFornecedores();
        for (Map<String, Object> fornecedor : fornecedores) {
            String nomeFornecedor = (String) fornecedor.get("razao_social");
            cbx_Fornecedor.addItem(nomeFornecedor.trim());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabelaProduto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbl_cnpj = new javax.swing.JLabel();
        lbl_endereco = new javax.swing.JLabel();
        txt_Fabricacao = new javax.swing.JTextField();
        txt_Nome = new javax.swing.JTextField();
        btm_Limpar = new javax.swing.JButton();
        btm_Alterar = new javax.swing.JButton();
        btm_cadastrar = new javax.swing.JButton();
        btm_excluir = new javax.swing.JButton();
        cbx_Fornecedor = new javax.swing.JComboBox<>();
        lbl_cnpj1 = new javax.swing.JLabel();
        btm_sair = new javax.swing.JButton();
        lbl_sejaBemVindo1 = new javax.swing.JLabel();
        lbl_MeroyLerlin = new javax.swing.JLabel();
        lbl_sejaBemVindo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Data de Fabricação", "Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(tbl_tabelaProduto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_cnpj.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_cnpj.setText("FORNECEDOR");

        lbl_endereco.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_endereco.setText("DATA DE FABRICAÇÃO");

        txt_Fabricacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FabricacaoActionPerformed(evt);
            }
        });

        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        btm_Limpar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btm_Limpar.setText("LIMPAR");
        btm_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_LimparActionPerformed(evt);
            }
        });

        btm_Alterar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btm_Alterar.setText("ALTERAR");
        btm_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_AlterarActionPerformed(evt);
            }
        });

        btm_cadastrar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btm_cadastrar.setText("CADASTRAR");
        btm_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_cadastrarActionPerformed(evt);
            }
        });

        btm_excluir.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btm_excluir.setText("EXCLUIR");
        btm_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_excluirActionPerformed(evt);
            }
        });

        cbx_Fornecedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbx_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_FornecedorActionPerformed(evt);
            }
        });

        lbl_cnpj1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_cnpj1.setText("NOME");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbx_Fornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Fabricacao, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btm_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btm_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btm_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btm_Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_cnpj)
                .addGap(180, 180, 180))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lbl_cnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Fabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lbl_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_cadastrar)
                    .addComponent(btm_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_Alterar)
                    .addComponent(btm_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lbl_cnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btm_sair.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btm_sair.setForeground(new java.awt.Color(255, 0, 0));
        btm_sair.setText("SAIR");
        btm_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_sairActionPerformed(evt);
            }
        });

        lbl_sejaBemVindo1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_sejaBemVindo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_sejaBemVindo1.setText("SEJA BEM VINDO À ");

        lbl_MeroyLerlin.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_MeroyLerlin.setForeground(new java.awt.Color(0, 204, 0));
        lbl_MeroyLerlin.setText("MEROY LERLIN");

        lbl_sejaBemVindo2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_sejaBemVindo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_sejaBemVindo2.setText("PRODUTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_sejaBemVindo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_MeroyLerlin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_sejaBemVindo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btm_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btm_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sejaBemVindo1)
                            .addComponent(lbl_MeroyLerlin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_sejaBemVindo2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FabricacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FabricacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FabricacaoActionPerformed

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void btm_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_LimparActionPerformed
        txt_Nome.setText("");
        txt_Fabricacao.setText("");
        tbl_tabelaProduto.clearSelection();
    }//GEN-LAST:event_btm_LimparActionPerformed

    private void btm_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_AlterarActionPerformed
        ProdutoConnection produtoConnection = new ProdutoConnection();
        int selectedRow = tbl_tabelaProduto.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela.");
            return;
        }

        int id = Integer.parseInt(tbl_tabelaProduto.getValueAt(selectedRow, 0).toString());

        String nome = txt_Nome.getText();
        String dataFabricacao = "";
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = dateFormat.parse(txt_Fabricacao.getText());
            SimpleDateFormat sqlDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            dataFabricacao = sqlDateFormat.format(date);
        } catch (ParseException e) {

        }

        String fornecedorSelecionado = cbx_Fornecedor.getSelectedItem().toString();

        produtoConnection.handleAlterarProduto(id, nome, dataFabricacao, fornecedorSelecionado);
        produtoConnection.handleSearch(tbl_tabelaProduto);
        txt_Nome.setText("");
        txt_Fabricacao.setText("");
        tbl_tabelaProduto.clearSelection();
    }//GEN-LAST:event_btm_AlterarActionPerformed

    private void btm_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_cadastrarActionPerformed
        ProdutoConnection produtoConnection = new ProdutoConnection();

        String nome = txt_Nome.getText();
        String dataFabricacao = "";
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = dateFormat.parse(txt_Fabricacao.getText());
            SimpleDateFormat sqlDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            dataFabricacao = sqlDateFormat.format(date);
        } catch (ParseException e) {
        }

        String fornecedorSelecionado = cbx_Fornecedor.getSelectedItem().toString();

        produtoConnection.handleCadastrarProduto(nome, dataFabricacao, fornecedorSelecionado);
        produtoConnection.handleSearch(tbl_tabelaProduto);
        txt_Nome.setText("");
        txt_Fabricacao.setText("");
        tbl_tabelaProduto.clearSelection();

    }//GEN-LAST:event_btm_cadastrarActionPerformed

    private void btm_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_sairActionPerformed
        int sair = JOptionPane.showConfirmDialog(this, "Voltar ao menu anterior?", "", 2);
        if (sair == 0) {
            Menu menu = new Menu();
            menu.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btm_sairActionPerformed

    private void btm_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_excluirActionPerformed
        ProdutoConnection produtoConnection = new ProdutoConnection();
        if (tbl_tabelaProduto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto na tabela.");
            return;
        }
        produtoConnection.handleExcluirProduto(Integer.parseInt(tbl_tabelaProduto.getValueAt(tbl_tabelaProduto.getSelectedRow(), 0).toString()));
        produtoConnection.handleSearch(tbl_tabelaProduto);
    }//GEN-LAST:event_btm_excluirActionPerformed

    private void cbx_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_FornecedorActionPerformed

    }//GEN-LAST:event_cbx_FornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_Alterar;
    private javax.swing.JButton btm_Limpar;
    private javax.swing.JButton btm_cadastrar;
    private javax.swing.JButton btm_excluir;
    private javax.swing.JButton btm_sair;
    private javax.swing.JComboBox<String> cbx_Fornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_MeroyLerlin;
    private javax.swing.JLabel lbl_cnpj;
    private javax.swing.JLabel lbl_cnpj1;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_sejaBemVindo1;
    private javax.swing.JLabel lbl_sejaBemVindo2;
    private javax.swing.JTable tbl_tabelaProduto;
    private javax.swing.JTextField txt_Fabricacao;
    private javax.swing.JTextField txt_Nome;
    // End of variables declaration//GEN-END:variables
}
